export const songList = [
  "Bohemian Rhapsody - Queen",
  "Imagine - John Lennon",
  "Billie Jean - Michael Jackson",
  "Like a Rolling Stone - Bob Dylan",
  "Hey Jude - The Beatles",
  "Purple Rain - Prince",
  "Smells Like Teen Spirit - Nirvana",
  "Sweet Child O' Mine - Guns N' Roses",
  "Hotel California - Eagles",
  "Stairway to Heaven - Led Zeppelin",
  "Yesterday - The Beatles",
  "Born to Run - Bruce Springsteen",
  "I Will Always Love You - Whitney Houston",
  "Like a Prayer - Madonna",
  "Sweet Dreams (Are Made of This) - Eurythmics",
  "Dancing Queen - ABBA",
  "Every Breath You Take - The Police",
  "Wonderwall - Oasis",
  "Sweet Home Alabama - Lynyrd Skynyrd",
  "Piano Man - Billy Joel",
  "American Woman - The Guess Who",
  "Bridge Over Troubled Water - Simon & Garfunkel",
  "Brown Eyed Girl - Van Morrison",
  "Sweet Caroline - Neil Diamond",
  "Dream On - Aerosmith"
];